const { app, BrowserWindow } = require('electron')
const net = require('node:net')
let socket
const windows = new Map()
const token = process.env.DSH_WEB_AGENT_RPC_TOKEN || process.argv[process.argv.indexOf('--rpc-token') + 1] || ''
function reply(id, ok, result, err) { if (!socket || socket.destroyed) return; socket.write(JSON.stringify(ok ? { id, ok: true, result } : { id, ok: false, err: String(err) }) + '\n') }
function sessionOf(id) { const s = windows.get(id); if (!s) throw new Error(`unknown browser session: ${id}`); return s }
function active(s) { if (!s.window || s.window.isDestroyed()) throw new Error('browser workspace window is closed'); return s.window.webContents }
async function evaluate(wc, expression) { const r = await wc.debugger.sendCommand('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text || 'page evaluation failed'); return r.result?.value }
async function handle(op, msg) {
  try {
    switch (op) {
      case 'ping': reply(msg.id,true,{ready:true}); return
      case 'createSession': { if (windows.has(msg.session)) { reply(msg.id,true,{created:false}); return }; const win=new BrowserWindow({width:1400,height:900,show:true,title:'Web-Agent Browser Workspace',webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}}); win.webContents.debugger.attach('1.3'); windows.set(msg.session,{id:msg.session,window:win,label:'Web-Agent'}); win.on('closed',()=>windows.delete(msg.session)); reply(msg.id,true,{created:true}); return }
      case 'setLabel': { const s=sessionOf(msg.session); s.label=typeof msg.label==='string'?msg.label:'Web-Agent'; s.window.setTitle(`${s.label} — Browser Workspace`); reply(msg.id,true,{label:s.label}); return }
      case 'navigate': { const s=sessionOf(msg.session); const url=new URL(String(msg.url)); if(url.protocol!=='http:'&&url.protocol!=='https:') throw new Error('only HTTP(S) URLs are allowed'); await active(s).loadURL(url.href); reply(msg.id,true,{url:active(s).getURL()}); return }
      case 'snapshot': { const s=sessionOf(msg.session); const value=await evaluate(active(s),`(() => { const nodes=[]; const selector='input,textarea,select,button,a[href],[role="button"],[contenteditable="true"]'; for(const el of document.querySelectorAll(selector)){const r=el.getBoundingClientRect(),c=getComputedStyle(el);if(r.width<4||r.height<4||c.display==='none'||c.visibility==='hidden')continue;const kind=el.tagName==='TEXTAREA'?'textarea':el.tagName==='INPUT'?'input':el.tagName==='BUTTON'?'button':el.tagName==='A'?'link':'other';const label=String(el.getAttribute('aria-label')||el.placeholder||el.innerText||el.textContent||el.value||el.title||'').replace(/\\s+/g,' ').trim().slice(0,160);nodes.push({ref:nodes.length+1,kind,label,value:el.value??undefined,selector:el.id?'#'+CSS.escape(el.id):'',x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)});if(nodes.length>=120)break}return{url:location.href,title:document.title||'',elements:nodes,readyState:document.readyState}})()`); reply(msg.id,true,value); return }
      case 'click': { const s=sessionOf(msg.session),wc=active(s); let x=Number(msg.x),y=Number(msg.y); if(msg.target){const t=msg.target,v=String(t.value||'');const js=t.by==='xpath'?`(() => { const r=document.evaluate(${JSON.stringify(v)},document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(!r)throw new Error('target not found');r.scrollIntoView({block:'center'});const b=r.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2} })()`:`(() => { const r=document.querySelector(${JSON.stringify(v)});if(!r)throw new Error('target not found');r.scrollIntoView({block:'center'});const b=r.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2} })()`;const p=await evaluate(wc,js);x=Number(p.x);y=Number(p.y)} if(!Number.isFinite(x)||!Number.isFinite(y))throw new Error('click requires coordinates or a CSS/XPath target');await wc.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1});await wc.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1});reply(msg.id,true,{ok:true});return }
      case 'fill': { const s=sessionOf(msg.session),wc=active(s),fields=Array.isArray(msg.fields)?msg.fields:[];const result=await evaluate(wc,`(() => { const fields=${JSON.stringify(fields)},out=[];const visible=e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e);return r.width>=4&&r.height>=4&&c.display!=='none'&&c.visibility!=='hidden'};for(const f of fields){let el=null;try{if(f.selector)el=document.querySelector(f.selector);else if(f.placeholder)el=[...document.querySelectorAll('input,textarea')].find(x=>x.placeholder===f.placeholder);else if(f.name)el=[...document.querySelectorAll('input,textarea,select')].find(x=>x.name===f.name)}catch{}if(!el||!visible(el)){out.push({ok:false,target:f.selector||f.placeholder||f.name||''});continue}const value=String(f.value??'');try{if(el.tagName==='TEXTAREA'){const s=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;s?s.call(el,value):el.value=value}else if(el.tagName==='INPUT'){const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;s?s.call(el,value):el.value=value}else if(el.isContentEditable)el.textContent=value;else el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));out.push({ok:true,target:f.selector||f.placeholder||f.name||''})}catch(e){out.push({ok:false,error:String(e),target:f.selector||f.placeholder||f.name||''})}}return{fields:out,submitted:false}})()`);if(msg.submit)await evaluate(wc,`(() => {const e=document.activeElement,f=e&&e.form;if(f){f.requestSubmit();return true}return false})()`);reply(msg.id,true,{...result,submitted:!!msg.submit});return }
      case 'key': { const s=sessionOf(msg.session),wc=active(s),key=String(msg.key),map={Enter:['Enter','Enter',13],Tab:['Tab','Tab',9],Escape:['Escape','Escape',27],Backspace:['Backspace','Backspace',8],Delete:['Delete','Delete',46],ArrowUp:['ArrowUp','ArrowUp',38],ArrowDown:['ArrowDown','ArrowDown',40],ArrowLeft:['ArrowLeft','ArrowLeft',37],ArrowRight:['ArrowRight','ArrowRight',39],Space:[' ','Space',32]},spec=map[key];if(!spec)throw new Error(`unsupported key: ${key}`);await wc.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyDown',key:spec[0],code:spec[1],windowsVirtualKeyCode:spec[2],nativeVirtualKeyCode:spec[2],...(key==='Space'?{text:' '}: {})});await wc.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyUp',key:spec[0],code:spec[1],windowsVirtualKeyCode:spec[2],nativeVirtualKeyCode:spec[2]});reply(msg.id,true,{ok:true});return }
      case 'scroll': { const s=sessionOf(msg.session),wc=active(s);await evaluate(wc,`(() => {if(${!!msg.toTop})window.scrollTo(0,0);else if(${!!msg.toBottom})window.scrollTo(0,document.body.scrollHeight);else window.scrollBy(${Number(msg.deltaX||0)},${Number(msg.deltaY||0)});return true})()`);reply(msg.id,true,{ok:true});return }
      case 'closeSession': { const s=windows.get(msg.session);if(s){try{s.window.close()}catch{}windows.delete(msg.session)}reply(msg.id,true,{closed:true});return }
      default: throw new Error(`unknown browser host operation: ${op}`)
    }
  } catch(e) { reply(msg.id,false,undefined,e instanceof Error?e.message:String(e)) }
}
app.whenReady().then(()=>{const pi=process.argv.indexOf('--rpc-port'),port=Number(process.argv[pi+1]);if(!Number.isFinite(port)){app.exit(1);return}socket=net.createConnection({host:'127.0.0.1',port});socket.setEncoding('utf8');socket.on('connect',()=>socket.write(JSON.stringify({id:0,op:'hello',token})+'\n'));let buffer='';socket.on('data',data=>{buffer+=data;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);if(!line)continue;try{const msg=JSON.parse(line);if(typeof msg.id==='number'&&typeof msg.op==='string')void handle(msg.op,msg)}catch{}}});socket.on('close',()=>app.quit());socket.on('error',()=>app.quit())})
